// <auto-generated />
using System;
using MMsWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MMsWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MMsWebApp.Models.Cetatean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cetateni");
                });

            modelBuilder.Entity("MMsWebApp.Models.Colectare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdPubela")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PubelaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdPubela");

                    b.HasIndex("PubelaId");

                    b.ToTable("Colectari");
                });

            modelBuilder.Entity("MMsWebApp.Models.Pubela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pubele");
                });

            modelBuilder.Entity("MMsWebApp.Models.PubelaCetatean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CetateanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PubelaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CetateanId");

                    b.HasIndex("PubelaId");

                    b.ToTable("PubeleCetateni");
                });

            modelBuilder.Entity("MMsWebApp.Models.Colectare", b =>
                {
                    b.HasOne("MMsWebApp.Models.Pubela", null)
                        .WithMany("Colectari")
                        .HasForeignKey("IdPubela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMsWebApp.Models.Pubela", "Pubela")
                        .WithMany()
                        .HasForeignKey("PubelaId");

                    b.Navigation("Pubela");
                });

            modelBuilder.Entity("MMsWebApp.Models.PubelaCetatean", b =>
                {
                    b.HasOne("MMsWebApp.Models.Cetatean", "Cetatean")
                        .WithMany("PubeleCetateni")
                        .HasForeignKey("CetateanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMsWebApp.Models.Pubela", "Pubela")
                        .WithMany("PubeleCetateni")
                        .HasForeignKey("PubelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cetatean");

                    b.Navigation("Pubela");
                });

            modelBuilder.Entity("MMsWebApp.Models.Cetatean", b =>
                {
                    b.Navigation("PubeleCetateni");
                });

            modelBuilder.Entity("MMsWebApp.Models.Pubela", b =>
                {
                    b.Navigation("Colectari");

                    b.Navigation("PubeleCetateni");
                });
#pragma warning restore 612, 618
        }
    }
}
